name: Primary Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:  # This allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Primary Workflow
        run: echo "Primary Workflow is running hehe!"

